spring.application.name=ecom_backend

spring.datasource.url=jdbc:mysql://localhost/ecom_backend_testing_4

spring.datasource.username=root
spring.datasource.password=abcd1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
