spring.application.name=ecom_backend

spring.datasource.url=jdbc:mysql://localhost/ecom_backend_testing_4

spring.datasource.username=root
spring.datasource.password=abcd1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

com.group.project.jwt.secret=++36xfSobeiERWDtfXGvtF1MTkxHITOKR0R8j/8OsTs=
com.group.project.jwt.expires-in=900

com.group.project.cookie.name=authToken
com.group.project.cookie.expires-in=900

spring.security.oauth2.client.registration.google.client-id=<client id>
spring.security.oauth2.client.registration.google.client-secret=<client secret>
